### ISSUE TITLE
No way to consistently override notification emails' "From:"

### ISSUE THREAD

**Issue by pfalcon** [git-multimail/git-multimail#160]
There's a very good configuration option for git-multimail - "from", which allows to override "From:" field of notification emails. Our users enjoy it very much, and it serves multiple usecases, including: 

* Not being guilty of spamming people completely unrelated to our *notification emails*. Consider for example that we mirror Linux kernel repo - hundreds of people don't want be subject of a random reply/send button hit, just because we mirror repository to which they contributed.
* Not requiring laborious configuration of mailing lists. For example, a mailing list can be configured to receive mail from a single bot account, to prevent spam acceptance, and not require daily maintenance to whitelist yet another person who contributed to Linux kernel.
* etc.

So, the option is great and works well. However, to our big surprise, this option gets ignored when a repository is accessed via Gerrit! Like, "multimail.from" is in .git/config and works as expected when accessed via a normal git daemon, but when the same repo is accessed via Gerrit, this method: https://github.com/git-multimail/git-multimail/blob/master/git-multimail/git_multimail.py#L3252 doesn't even try to consider it.

Please note that I describe usecases above in the detail to make a point that the problem is not "gerrit environment ignores multimail.from option", but "git-multimail should provide means to unconditionally set From: for any generated emails - regardless of an environment a repository is accessed via".

@moy : Would you agree with such formulation? If so, should we prepare a patch, or maybe you have something like that in your queue already?

Thanks!

**Comment by moy** [comment]
Hi,

No time for a detailed response, but in short:

* I don't use gerrit, so I happily accept patches for it but I don't have anything in my queue.

* Gerrit support was contributed by @newren, he probably has more to say than I. I can't say whether the current behavior is intentional.

* The Environment class is a mixin, functions are considered going through the list of components of the mixin: each function can either return a value, or transmit the call to the next class using `super`. The line of code you link to "considers" all options in the `else` clause, but it's not executed because `__submitter` is set, and currently takes precedence over it. Probably we should reverse the precedence.

**Comment by pfalcon** [comment]
@moy: Thanks, and that's pretty detailed already ;-). I imagined that it could be that Gerrit support was contributed ans stays mostly as is after that, thanks for confirming that.

> The Environment class is a mixin, functions are considered going through the list of components of the mixin: each function can either return a value, or transmit the call to the next class using super. The line of code you link to "considers" all options in the else clause, but it's not executed because __submitter is set, and currently takes precedence over it. Probably we should reverse the precedence.

Yes, so this "chain of mixins" design is flexible, and actually, "global override" I'm talking about could be implemented using a mixin to be tackled at the front of mixin list for each environment. My colleague @doanac will likely work on the details though, I just wanted to be sure that he seriously considers resolving it in upstream, instead of forking/finding another workaround.

**Comment by newren** [comment]
A global override sounds fine.  However, going through the chain of mixins for get_fromaddr() and only using submitter when none of those return a value, though, would be a really big problem, because those always return a value and not a very useful one.  The base class, I believe, returns user.name and user.email, which is the same hardcoded value and in my usecase, we want emails to come from whoever pushed the code.

If we could set things up so that multimail.from was top priority, then submitter, then other fallbacks (like user.name/user.email) then that'd be totally fine by me.

**Comment by moy** [comment]
Let's discuss this in #164.
