### ISSUE TITLE
Omit email body between header and footer template

### ISSUE THREAD

**Issue by JayEn84** [git-multimail/git-multimail#174]
Hey all,

I'd like to send a really short info email containing the information that someone pushed something into my repo, but without the detailed information. I did not find a way to omit the actual body between the header and footer templates without changing the .py file. Maybe, a config setting like

```
[multimailhook]
    omitDetailInfo = true
```

could be used.

**Comment by moy** [comment]
For your use-case, I'd suggest not sending commit notifications, but only refchange notifications (i.e. just one email per push), and set `multimailhook.refchangeShowLog` (possibly with `multimailhook.logOpts` to customize it).

Otherwise, you can tweak `multimailhook.logOpts` to reduce the information it shows (typically remove `-p` from the default value to remove the patch).

Does this work for you? If not, what would your email bodies look like ideally?

**Comment by JayEn84** [comment]
Thanks @moy ! In the config file, I replaced `mailingList` with `refchangeList` so that commit notifications are not sent. Also, I added the two lines 
```
        refchangeShowLog = true
        logOpts = --oneline --no-walk
```

and the email which is sent then is pretty much what I was looking for. Unfortunately, it seems there is no possibility to send the refchange emails in HTML format, but that's not mandatory.

So, problem solved, thanks a lot!

**Comment by moy** [comment]
> Unfortunately, it seems there is no possibility to send the refchange emails in HTML format, but that's not mandatory.

You're right. HTML makes a lot of sense for commit notifications, since the pretty-printing of the diff really has some added value. It is much less true for refchange notifications so it's currently not implemented (I'd welcome patches to do so and I may even work on this myself, but it's clearly very low priority).
